server:
  port: 8899

spring:
  cloud:
    gateway:
      routes:
        - id: clients_ms_clients
          uri: http://localhost:8081
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients/(?<path>.*), /api/clients/$\{path}

        - id: clients_ms_groupes
          uri: http://localhost:8081
          predicates:
            - Path=/groupes-clients/**
          filters:
            - RewritePath=/groupes-clients/(?<path>.*), /api/groupes-clients/$\{path}

        - id: articles_ms
          uri: http://localhost:8091
          predicates:
            - Path=/articles/**
          filters:
            - RewritePath=/articles/(?<path>.*), /api/articles/$\{path}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis
