server:
  port: 8899

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: clients_ms_clients
          uri: lb://CLIENT-MS
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients/(?<path>.*), /api/clients/${path}

        - id: clients_ms_groupes
          uri: lb://CLIENT-MS
          predicates:
            - Path=/groupes-clients/**
          filters:
            - RewritePath=/groupes-clients/(?<path>.*), /api/groupes-clients/${path}

        - id: articles_ms
          uri: lb://ARTICLE-MS
          predicates:
            - Path=/articles/**
          filters:
            - RewritePath=/articles/(?<path>.*), /api/articles/${path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
