server:
  port: 8899

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: clients_ms_clients
          uri: lb://clients-ms
          predicates:
            - Path=/client/**

        - id: articles_ms
          uri: lb://article-ms
          predicates:
            - Path=/articles/**

        - id: stock_ms
          uri: lb://stock-ms
          predicates:
            - Path=/stocks/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
