server:
  port: 8899

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: client_ms
          uri: lb://client-ms
          predicates:
            - Path=/client/**

        - id: article_ms
          uri: lb://article-ms
          predicates:
            - Path=/article/**
        
        - id: magasin_ms
          uri: lb://magasin-ms
          predicates:
            - Path=/magasin/**

        - id: stock_ms
          uri: lb://stock-ms
          predicates:
            - Path=/stock/**

        - id: vente_ms
          uri: lb://vente-ms
          predicates:
            - Path=/vente/**
        
        - id: livraison_ms
          uri: lb://livraison-ms
          predicates:
            - Path=/livraison/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


springdoc:
  swagger-ui:
    urls:
      - name: Vente Microservice
        url: http://locahost:8899/vente/vente-ms/v3/api-docs
      - name: Livraison Microservice
        url: /livraison/v3/api-docs
  api-docs:
    enabled: false
