spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@192.168.0.123:27017/article-ms?authSource=admin
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis
      authorizationserver:
        endpoint:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
          
jwt:
  auth:
    converter:
      resource-id: artis-rest-api
      principle-attribute: preferred_username
server:
  port: 8095
