spring:
  mvc:
    servlet:
      path: /livraison-ms
      
  datasource:
    url: jdbc:postgresql://192.168.0.123:6588/livraison_ms
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis
      authorizationserver:
        endpoint:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  rabbitmq:
    host: 192.168.0.124
    port: 30672
    username: admin
    password: admin123

jwt:
  auth:
    converter:
      resource-id: artis-rest-api
      principle-attribute: preferred_username
      
server:
  port: 8096

livraison:
  rabbitmq:
    exchange: livraison-stock-exchange
    routing-key: livraison.stock.update
    queue: livraison-stock-queue