spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magasin-ms
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis
      authorizationserver:
        endpoint:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jw
jwt:
  auth:
    converter:
      resource-id: artis-rest-api
      principle-attribute: preferred_username
