spring:
  mvc:
    servlet:
      path: /stock

  datasource:
    url: jdbc:postgresql://192.168.0.123:6588/stock_ms
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.116:8180/realms/artis
      authorizationserver:
        endpoint:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  rabbitmq:
    host: 192.168.0.124
    port: 30672
    username: admin
    password: admin123

jwt:
  auth:
    converter:
      resource-id: artis-rest-api
      principle-attribute: preferred_username
      
server:
  port: 8094

stock:
  rabbitmq:
    queue: livraison-stock-queue
